services:
  resource-planner:
    build:
      context: .
      args:
        VERSION: "0.4"
    image: resource-planner:0.4
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Nick's Super Great Resource Planner
      - APP_VERSION=0.4
    volumes:
      - planner-data:/app/instance
      - ./config.json:/app/config.json
    restart: unless-stopped

volumes:
  planner-data:
