services:
  resource-planner:
    build:
      context: .
      args:
        VERSION: "0.2"
    image: resource-planner:0.2
    ports:
      - "5000:5000"
    volumes:
      - planner-data:/app/instance
      - ./config.json:/app/config.json
    restart: unless-stopped

volumes:
  planner-data:
